executor: "LocalExecutor"
config:
  scheduler:
    dag_dir_list_interval: 10
  core:
    dags_folder: "/usr/local/airflow/dags"

webserverSecretKey: "basickey"

triggerer:
  extraVolumeMounts: # this will get the volume and mount it to that path in the container                                                                                                                                                               
  - name: dags
    mountPath: /usr/local/airflow/dags  # location in the container it will put the directory mentioned below.

  extraVolumes: # this will create the volume from the directory
  - name: dags
    hostPath:
      path: "/data/dags"  # For you this is something like /home/*user*/github/airflowDAGs/dags

# Airflow scheduler settings
scheduler:
  # Mount additional volumes into scheduler.
  extraVolumeMounts: # this will get the volume and mount it to that path in the container                                                                                                                                                               
  - name: dags
    mountPath: /usr/local/airflow/dags  # location in the container it will put the directory mentioned below.

  extraVolumes: # this will create the volume from the directory
  - name: dags
    hostPath:
      path: "/data/dags"  # For you this is something like /home/*user*/github/airflowDAGs/dags
